version: '3'
services:
    db:
        image: library/mysql:8.0.21
        volumes:
            - ".data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
        ports:
            - "3306:3306"
    java:
        build: .
        volumes:
          - ".:/var/www/html"
        ports:
            - 9000:8000
    vue-ui:
        build: ./app
        ports:
            - "8080:8080"
        container_name: vue-ui
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
